### PR TITLE
add changelog for v0.3.0 release

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- add changelog for v0.3.0 release

#### Ticket Link
n/a

#### Release Note

```release-note
add changelog for v0.3.0 release
```

### CODE REVIEW

**Review by priyawadhwa — APPROVED** [review]
LGTM!

**Comment by dlorenc** [comment]
Do we want #496 to go in first, or after?

**Comment by cpanato** [comment]
@dlorenc this is a post changelog for v0.3.0 😅  v0.3.0 is already released

**Comment by haydentherapper** [comment]
That's all good if https://github.com/sigstore/fulcio/pull/496 isn't in. https://github.com/sigstore/fulcio/pull/496 and https://github.com/sigstore/fulcio/pull/507 can be in the next release.

**Comment by cpanato** [comment]
> That's all good if #496 isn't in. #496 and #507 can be in the next release.

we can release v0.4.0 next week

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
