### PR TITLE
Set odic email contacts / uris the same

### PR DESCRIPTION
**Pull request by lukehinds**
Signed-off-by: Luke Hinds <lhinds@redhat.com>

### CODE REVIEW

**Review by haydentherapper — CHANGES_REQUESTED** [review]
I don’t believe this is a valid domain, unless we’ve spun one up that’s I’m not aware of.

I don’t know if Dan still is hosting this example either. could we just remove it?

**Comment by lukehinds** [comment]
I don't believe they are meant to resolve anything, but at the time we did not have sigstore.dev, so figured now we do, may as well have them set to our domain, so anyone can figure out the originating service.

**Comment by haydentherapper** [comment]
These are meant to be the production values, not just examples, so we should have a resolvable service hosted at this endpoint if we specify it. We copy this config over to production. I think we should just remove the dlorenc SPIFFE endpoint since no one should be using that anyways. 

The contact updates LGTM.

**Comment by haydentherapper** [comment]
These are meant to be the production values, not just examples, so we should have a resolvable service hosted at this endpoint if we specify it. We copy this config over to production. I think we should just remove the dlorenc SPIFFE endpoint since no one should be using that anyways. 

The contact updates LGTM.

**Comment by haydentherapper** [comment]
Closing in favor of https://github.com/sigstore/fulcio/pull/932

**Pull request closed without merging**
