### PR TITLE
add changelog for v0.4.0

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- add changelog for v0.4.0

#### Ticket Link
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by cpanato** [comment]
> Can we get #527 in first since this changes the grpc api?

yes sir! 😃

**Comment by k4leung4** [comment]
Looks like #527 landed.
can we update the changelog with the #527 enhancement?

thanks

**Comment by cpanato** [comment]
> Looks like #527 landed. can we update the changelog with the #527 enhancement?
> 
> thanks

added! :)

**Comment by cpanato** [comment]
@k4leung4 @haydentherapper @dlorenc PTAL

**Review by k4leung4 — APPROVED** [review]
Thank you

**Review by dlorenc — APPROVED** [review]

**Review by haydentherapper — APPROVED** [review]

**Comment by cpanato** [comment]
@dlorenc ping to merge this, i dont have permissions to merge

**Pull request merged**
