### PR TITLE
Fix fulcio config

### PR DESCRIPTION
**Pull request by priyawadhwa**
currently panics because the config is not parseable

### CODE REVIEW

**Review by cpanato — APPROVED** [review]

**Comment by bobcallaway** [comment]
No issue with the change, but how was this not caught in CI?

**Comment by cpanato** [comment]
@bobcallaway good question. I will take a look in the CI tomorrow and fix it

**Comment by cpanato** [comment]
@bobcallaway checked and this file (and the directory) is not being used in CI and not being validated if the yaml manifest is correct. I will propose a PR to add some basic yamllint/k8s validation in those things.

**Comment by cpanato** [comment]
this change was merged in #118 
we can close this PR
that so much for your contribution!

**Pull request closed without merging**
