### PR TITLE
Add an option to skip clientID checks  for OIDC issuers

### PR DESCRIPTION
**Pull request by hectorj2f**
Signed-off-by: Hector Fernandez <hector@chainguard.dev>

#### Summary

We should expose an option to skip the ClientID verification for the OIDC Issuers on demand.

#### Release Note

Add option to skip the ClientID verifications for the configured OIDC Issuers.

### CODE REVIEW

**Review by haydentherapper — COMMENTED** [review]
What is the reason for this change? I would prefer we not make this optional, this is a part of OIDC token verification.

**Comment by hectorj2f** [comment]
@haydentherapper Yes, I understand it is not ideal. But we want to tell Fulcio to skip checking the token’s audience on-demand.

**Comment by haydentherapper** [comment]
I'm still uncertain why that would be needed unless you're testing with malformed tokens. A token should always contain an audience, and that audience should be static per provider. Fulcio operators should not be able to ignore audience, that opens them up to some risk.

**Comment by hectorj2f** [comment]
We aren't using malformed tokens. This is only required for OIDC issuer types working with Github-Actions. We need to instruct Fulcio to skip clientID checks, or enable Fulcio to accept custom issuer types which isn't possible today.  
cc @priyawadhwa

**Comment by haydentherapper** [comment]
GitHub Actions supports setting a custom audience, that’s what’s currently done when GHAs call fulcio.

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#:~:text=you%20can%20set%20a%20custom%20audience%20with%20a%20toolkit%20command%3A%20core.getidtoken(audience)

I also don’t think OIDC token verifiers should accept multiple client IDs, you should be given tokens for an expected audience.

**Comment by haydentherapper** [comment]
The spec allows for multiple audiences, so it would be fine if we supported multiple audiences (albeit I’m not sure the use case) - https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

We aren’t going to add something that allows for deviation from the spec and a potential foot-gun for service operators.

**Comment by hectorj2f** [comment]
@haydentherapper Sorry for my late reply! Thanks for the comments. We'll reconsider our alternatives here and attempt a different approach.

**Comment by haydentherapper** [comment]
@hectorj2f Good to close this PR?

**Comment by haydentherapper** [comment]
Closing since I believe the other PRs will supersede this, lemme know if not.

**Pull request closed without merging**
