### PR TITLE
Allow for multiple OIDC providers.

### PR DESCRIPTION
**Pull request by dlorenc**
Signed-off-by: Dan Lorenc <dlorenc@google.com>

### CODE REVIEW

**Comment by dlorenc** [comment]
I think we might want a way to "hint" at the proper issuer via a header or query parameter here. We could pull it out of the JWT itself, but that seems more error-prone.

Going through them in a list is fine but we should probably add the hint if we want to support more than a few.

**Comment by lukehinds** [comment]
What's the use case here, is it fail over type system if the first provider is unavailable (iterate over several providers?)

**Comment by dlorenc** [comment]
> What's the use case here, is it fail over type system if the first provider is unavailable (iterate over several providers?)

Left some more text in the description, but I think this would make eventual federation and headless modes easier.

**Review by bobcallaway — APPROVED** [review]
use case makes sense... would be nice to specify client ID separately for each issuer but for now this should be fine

**Review by lukehinds — APPROVED** [review]

**Comment by dlorenc** [comment]
> use case makes sense... would be nice to specify client ID separately for each issuer but for now this should be fine

Opened #100 to track that

**Pull request merged**
