### PR TITLE
CTL Chain Inclusion

### PR DESCRIPTION
**Pull request by lukehinds**
Signed-off-by: Luke Hinds <lhinds@redhat.com>

### CODE REVIEW

**Comment by dlorenc** [comment]
Nice! I'll give this a try.

**Comment by lukehinds** [comment]
still a few things to do:

- [ ] unit tests
- [ ] URL and params handler

**Comment by dlorenc** [comment]
> * [ ]  URL and params handler

What did you mean by this part?

**Comment by lukehinds** [comment]
> > * [ ]   URL and params handler
> 
> What did you mean by this part?

You just pushed  part of that (grab the url from viper) and then add the api version uri ({prefix}/app/v1/)

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
