### PR TITLE
Update Fulcio to 1.20

### PR DESCRIPTION
**Pull request by haydentherapper**
Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

### CODE REVIEW

**Comment by haydentherapper** [comment]
@cpanato, would you be able to create a new release of `golang-cross` for 1.20?

**Comment by cpanato** [comment]
> @cpanato, would you be able to create a new release of `golang-cross` for 1.20?

i will do

**Comment by haydentherapper** [comment]
Thank you! I'll update the PR once it's out

**Comment by haydentherapper** [comment]
@cpanato Looks like we're still seeing the goreleaser validation fail. Do you know what the root cause is? Do we need to update goreleaser in golang-cross?

**Comment by cpanato** [comment]
> @cpanato Looks like we're still seeing the goreleaser validation fail. Do you know what the root cause is? Do we need to update goreleaser in golang-cross?

need to do the same thing i did here https://github.com/sigstore/cosign/pull/2689/files#diff-069ba9578a5f0a93f6228a8bce7a77ac66e2beb5d6be1dcddad046868801f96aR53-R63

**Comment by haydentherapper** [comment]
Thanks @cpanato that worked!

**Review by cpanato — APPROVED** [review]
thank you

**Pull request merged**
