### PR TITLE
Upgrade fulcios to use of the google privateca api at v1

### PR DESCRIPTION
**Pull request by n3wscott**
Signed-off-by: Scott Nichols <n3wscott@chainguard.dev>

#### Summary

We were still on a v1beta1 api for the googleca private ca. This adds a flag to use the v1 of the api. We are still needing to update the cert to `v1`.

The new flag `--gcp_private_ca_version` selects `v1` by default to allow us to drop the flag when we move to v1 certs and then delete the flag and the v1beta1 codepaths.

#### Ticket Link

Relates to a checkbox in https://github.com/sigstore/fulcio/issues/191

#### Release Note

```release-note
Fulcio now can use the v1 api for google privateca.
```

### CODE REVIEW

**Comment by haydentherapper** [comment]
I'm working on updating this PR.

**Comment by n3wscott** [comment]
sorry @haydentherapper I just updated it!

**Comment by haydentherapper** [comment]
Thanks @n3wscott! Is there anything else that needs to be updated with the PR now?

**Review by mattmoor — APPROVED** [review]
This LGTM.  @bobcallaway anything else?

**Review by bobcallaway — APPROVED** [review]
LGTM

**Comment by n3wscott** [comment]
@haydentherapper we need to use the new V1 cert and change the flags we use to start the server. I am a little unclear how that works

**Comment by dlorenc** [comment]
@asraa and I caught up yesterday. There's one more missing PR in cosign to add the new root cert, then we can test this!

**Pull request merged**
