### PR TITLE
update builder release to use go 1.19.5

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- update builder release to use go 1.19.5

### CODE REVIEW

**Review by haydentherapper — APPROVED** [review]

**Comment by haydentherapper** [comment]
hm, keeps timing out.

**Comment by cpanato** [comment]
> @cpanato Do you think this is worth getting into a new cut of Fulcio? if so, i'll hold off until it's ready

are we planning to make any fulcio 1.x release or focus only on 2.0? if no plans maybe we can close this

**Comment by haydentherapper** [comment]
2.0 is a ways out, I just filed an issue to keep track of what I want it to contain. I'm planning to cut a 1.1 release from HEAD once https://github.com/sigstore/fulcio/pull/931 is in. Ideally we could also use 1.19.5 and get this PR in too.

**Comment by cpanato** [comment]
> 2.0 is a ways out, I just filed an issue to keep track of what I want it to contain. I'm planning to cut a 1.1 release from HEAD once https://github.com/sigstore/fulcio/pull/931 is in. Ideally we could also use 1.19.5 and get this PR in too. 

I think we can merge this, the ci failures are not related to this change

**Comment by haydentherapper** [comment]
I think we should just skip this release and go straight to 1.20 (i created a new PR)

**Pull request closed without merging**
