### PR TITLE
fallback to json default cfg path if yaml does not exist

### LINKED ISSUE #1811: config default path changed
**Description**

The config default path changed in https://github.com/sigstore/fulcio/pull/1720. Breaking setups without explicit configured path.

**Version**

### PR DESCRIPTION
**Pull request by miyunari**
Closes #1811

#### Summary
The PR #1720 has changed the default config path from `/etc/fulcio-config/config.json` to `/etc/fulcio-config/config.yaml`. This caused problems with non-explicitly configured environments.

#### Release Note

Check and fallback to default JSON config if the default YAML configuration file did not exist.

### CODE REVIEW

**Review by haydentherapper — APPROVED** [review]
Thanks!

**Comment by haydentherapper** [comment]
Will need to rebase once https://github.com/sigstore/fulcio/pull/1814 merges.

**Comment by haydentherapper** [comment]
Needs a rebase.

**Comment by miyunari** [comment]
> Needs a rebase.

Sry @haydentherapper, just saw this and rebased it now :+1:

**Review by cpanato — APPROVED** [review]

**Pull request merged**
