### PR TITLE
WIP: Use precertificates to embed SCT's in issued certs

### PR DESCRIPTION
**Pull request by priyawadhwa**
This is still a WIP -- certs are being issued but I still have to validate the embedded SCT against the CT log public key.

But right now the PR adds in the following:
1. Request a precertificate, with a poison extension to invalidate it
2. Submit the precert to the CT log, get back an SCT
3. Request an actual cert, with the SCT embedded
4. Submit the actual cert to the CT log as well

Fixes https://github.com/sigstore/fulcio/issues/42

### CODE REVIEW

**Comment by dlorenc** [comment]
> * Request a precertificate, with a poison extension to invalidate it

Nit: I think the spelling is technically "priya-certificate".

**Comment by dlorenc** [comment]
This is amazing!

**Comment by lukehinds** [comment]
did you mean to close this @priyawadhwa ? it was coming on well.

**Comment by priyawadhwa** [comment]
hey @lukehinds unfortunately it looks like this won't work right now, I explained why in this comment! https://github.com/sigstore/fulcio/issues/42#issuecomment-807104461

Hopefully we can come back to it in the future

**Pull request closed without merging**
