### PR TITLE
Fix misspellings.

### PR DESCRIPTION
**Pull request by msuozzo**
s/Fuclio/Fulcio/

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
LGTM
thanks!

**Comment by cpanato** [comment]
@msuozzo please sign the CLA

**Comment by msuozzo** [comment]
How do I sign the CLA? Did you mean signoff on the commit?

**Comment by cpanato** [comment]
> How do I sign the CLA? Did you mean signoff on the commit?

Yes, Sorry messed the repos, here you need to aign the commit (DCO)

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
