### PR TITLE
Federate with Arch Linux's GitLab instance

### PR DESCRIPTION
**Pull request by klausenbusk**
#### Summary
We want to federate so we can sign our container image[1] and perhaps more in the future.

[1] https://gitlab.archlinux.org/archlinux/archlinux-docker/

### CODE REVIEW

**Comment by aladh** [comment]
This is great! Please let me know if you have any feedback about using GitLab with sigstore. FYI we're making some changes to the certificate mapping: https://github.com/sigstore/fulcio/pull/1206.

**Comment by haydentherapper** [comment]
Thanks for adding this! Have you gotten a chance to test this out with a local instance of fulcio?

**Review by haydentherapper — APPROVED** [review]
Thanks for testing this out! Really happy to see that this worked for you.

I'll get this merged and rolled out to our staging instance in the next day or so. To test, follow https://docs.sigstore.dev/cosign/public_deployment/#usage, which uses a different root of trust and URL for accessing staging.

I'll ping the issue once it's deployed.

**Comment by haydentherapper** [comment]
@klausenbusk Change has been rolled out to staging. Can you give it a try?

**Comment by klausenbusk** [comment]
This is mostly working with this `.gitlab-ci.yml`:
```yaml
sleep:
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
    - pacman -Syu --needed --noconfirm skopeo cosign
    - skopeo login "${CI_REGISTRY}" -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"
    - skopeo copy docker://docker.io/archlinux/archlinux:latest "docker://${CI_REGISTRY_IMAGE}:${CI_JOB_ID}"
    - mkdir ~/.docker
    - cp /run/containers/0/auth.json ~/.docker/config.json
    - curl -sSfO https://raw.githubusercontent.com/sigstore/root-signing/main/staging/repository/1.root.json
    - cosign initialize --mirror=https://tuf-repo-cdn.sigstage.dev/ --root=1.root.json
    - cosign sign --yes --oidc-issuer "https://gitlab.archlinux.org" --fulcio-url "https://fulcio.sigstage.dev" --rekor-url "https://rekor.sigstage.dev" "${CI_REGISTRY_IMAGE}:${CI_JOB_ID}"
    - cosign verify "${CI_REGISTRY_IMAGE}:${CI_JOB_ID}" --rekor-url "https://rekor.sigstage.dev" --certificate-identity "https://gitlab.com/klausenbusk/fulcio-test@refs/heads/master" --certificate-oidc-issuer "https://gitlab.archlinux.org"
    - cosign verify "${CI_REGISTRY_IMAGE}:${CI_JOB_ID}" --rekor-url "https://rekor.sigstage.dev" --certificate-identity "https://gitlab.archlinux.org/klausenbusk/fulcio-test@refs/heads/master" --certificate-oidc-issuer "https://gitlab.archlinux.org"
```
*log [here](https://gitlab.archlinux.org/klausenbusk/fulcio-test/-/jobs/157883)*

But as it can be seen from the last command, the subject is incorrect (it was also incorrect in my earlier testing (https://github.com/sigstore/fulcio/pull/1214#issuecomment-1588030117), but I somehow missed it):
```
none of the expected identities matched what was in the certificate, got subjects [https://gitlab.com/klausenbusk/fulcio-test@refs/heads/master] with issuer https://gitlab.archlinux.org/
```

Reading the code, the URL is hardcoded to `https://gitlab.com/` here:
https://github.com/sigstore/fulcio/blob/1beb42991616b0f3f3773450992d2d6f7508c860/pkg/identity/gitlabcom/principal.go#L156

I would assume changing it to `url:               token.Issuer,` should work, but maybe I'm missing something, since it wasn't done this way initially?

**Comment by klausenbusk** [comment]
@cpanato maybe you can shed some light on, why the url is hard-coded to `https://gitlab.com` instead of using e.g. the issuer? It is causing a incorrect subject (see ^).

**Comment by haydentherapper** [comment]
This is meant to be a fixed string, while the Issuer extension represents the specific instance of the identity provider. For example for GitHub, we chose to just use “GitHub.com” even though the issuer is something like “tokens.actions.GitHub.com”.

**Comment by cpanato** [comment]
what @haydentherapper said :)

**Comment by klausenbusk** [comment]
Thanks for clearing up that misunderstanding :)

**Comment by haydentherapper** [comment]
@klausenbusk It's now rolled out to production. Lemme know if there's any issues.

**Comment by klausenbusk** [comment]
It seems to work🎉 and I have created [a MR](https://gitlab.archlinux.org/archlinux/archlinux-docker/-/merge_requests/77) so we can start signing our container images.

@haydentherapper I noticed that the OIDs embedded in the certificate, are also using `gitlab.com` instead of `gitlab.archlinux.org`, is the expected?

E.g. Build Signer URI, Source Repository URI, Source Repository Owner URI, Build Config URI and Run Invocation URI.

```sh
$ cosign verify "registry.archlinux.org/klausenbusk/fulcio-test:160161" --certificate-identity "https://gitlab.com/klausenbusk/fulcio-test@refs/heads/master" --certificate-oidc-issuer "https://gitlab.archlinux.org" 2>/dev/null | jq -r .[0].optional.Bundle.Payload.body | base64 -d | jq -r .spec.signature.publicKey.content | base64 -d | openssl x509 -text -noout -in /dev/stdin
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0e:18:6d:1a:e9:82:1c:e1:9e:11:09:49:1c:df:f3:14:bb:5d:32:8d
        Signature Algorithm: ecdsa-with-SHA384
        Issuer: O = sigstore.dev, CN = sigstore-intermediate
        Validity
            Not Before: Jun 23 21:14:12 2023 GMT
            Not After : Jun 23 21:24:12 2023 GMT
        Subject: 
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:1c:b6:62:23:94:a3:e5:8a:9f:24:3c:df:96:e6:
                    f4:e7:25:1f:67:8b:b3:f5:bf:52:8c:63:22:85:69:
                    2d:30:0f:19:fe:60:e4:f4:1c:41:82:84:d7:d5:a9:
                    ad:90:7d:f3:62:78:8d:2d:b7:60:3e:d7:af:4a:37:
                    2f:d3:2b:c9:b4
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Extended Key Usage: 
                Code Signing
            X509v3 Subject Key Identifier: 
                D2:5D:C1:92:E9:45:A0:03:63:54:12:5F:26:49:1D:12:97:51:36:AA
            X509v3 Authority Key Identifier: 
                DF:D3:E9:CF:56:24:11:96:F9:A8:D8:E9:28:55:A2:C6:2E:18:64:3F
            X509v3 Subject Alternative Name: critical
                URI:https://gitlab.com/klausenbusk/fulcio-test@refs/heads/master
            1.3.6.1.4.1.57264.1.1: 
                https://gitlab.archlinux.org
            1.3.6.1.4.1.57264.1.8: 
                ..https://gitlab.archlinux.org
            1.3.6.1.4.1.57264.1.9: 
                .8https://gitlab.com/klausenbusk/fulcio-test/-/jobs/160161
            1.3.6.1.4.1.57264.1.11: 
                ..self-hosted
            1.3.6.1.4.1.57264.1.12: 
                .*https://gitlab.com/klausenbusk/fulcio-test
            1.3.6.1.4.1.57264.1.13: 
                .(c7d3e3bfeafc85ca4a56f4daa29fbf7c51cb535f
            1.3.6.1.4.1.57264.1.14: 
                ..refs/heads/master
            1.3.6.1.4.1.57264.1.15: 
                ..44402
            1.3.6.1.4.1.57264.1.16: 
                ..https://gitlab.com/klausenbusk
            1.3.6.1.4.1.57264.1.17: 
                ..85
            1.3.6.1.4.1.57264.1.18: 
                .8https://gitlab.com/klausenbusk/fulcio-test/-/jobs/160161
            1.3.6.1.4.1.57264.1.20: 
                ..push
            1.3.6.1.4.1.57264.1.21: 
                .<https://gitlab.com/klausenbusk/fulcio-test/-/pipelines/70893
            CT Precertificate SCTs: 
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : DD:3D:30:6A:C6:C7:11:32:63:19:1E:1C:99:67:37:02:
                                A2:4A:5E:B8:DE:3C:AD:FF:87:8A:72:80:2F:29:EE:8E
                    Timestamp : Jun 23 21:14:12.163 2023 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:46:02:21:00:EB:64:18:AC:B2:D0:80:38:49:E8:77:
                                83:E6:7E:95:F9:81:72:A8:52:E8:BD:1D:49:65:8F:B7:
                                30:5A:87:BA:6D:02:21:00:E3:92:D6:4F:A1:95:25:85:
                                5A:44:E4:A7:74:FA:EB:8D:17:F5:0D:71:12:AC:6C:0F:
                                08:B1:4E:B0:6B:27:DD:20
    Signature Algorithm: ecdsa-with-SHA384
    Signature Value:
        30:65:02:30:0d:b7:ac:b5:29:c8:c2:bd:47:c7:3e:57:0d:81:
        42:16:04:ca:2b:4a:ec:ba:71:12:7a:4e:9a:9f:ec:ed:6a:a2:
        32:0a:94:58:ae:84:36:bc:1c:14:11:7a:81:34:a9:92:02:31:
        00:87:a2:c3:62:80:9a:e7:0a:56:65:fc:e1:b3:6d:83:2b:5a:
        82:ef:d6:f0:10:68:24:02:26:47:8e:cc:fb:7a:7b:c6:f6:28:
        dc:85:00:a4:ed:db:b7:c5:ce:07:ad:61:70
```

**Comment by haydentherapper** [comment]
That’s for the same reasons as above. A verifier will create a verification policy that should look the same regardless of which Gitlab (or other CI) instance they verify against, except for the issuer, which will differ.

If you see any issue with this, we can chat about changing this.

**Pull request merged**
