### PR TITLE
Implement Basic CI

### PR DESCRIPTION
**Pull request by lukehinds**
No e2e run as yet, until we have some in place.

Signed-off-by: Luke Hinds lhinds@redhat.com

### CODE REVIEW

**Comment by lukehinds** [comment]
This is fixed now, just needs the openapi PR merged first

```
Run swagger validate openapi.yaml
open openapi.yaml: no such file or directory
Error: Process completed with exit code 1.
```

**Comment by lukehinds** [comment]
ok, I guess we need to park this one until some code is in :)

**Comment by lukehinds** [comment]
added the development branch

**Comment by lukehinds** [comment]
@dlorenc / @bobcallaway  can we ship this one, we don't have coverage of the development branch at present?

**Comment by lukehinds** [comment]
the failure is a follow up commit with no sig and you can't see to retroffix (likely a bug with the bot)

**Review by bobcallaway — APPROVED** [review]

**Pull request merged**
