### PR TITLE
Support enterprise-unique GitHub Actions OIDC issuer URLs

### PR DESCRIPTION
**Pull request by reedloden**
#### Summary

GitHub Actions supports enterprise-specific OIDC issuer URLs for security hardening reasons. However, `fulcio` only supports the default issuer URL. Add an additional meta issuer to cover such special-cased issuer URLs.

Resolves sigstore/fulcio#1087.

#### Release Note

Added support for GitHub Actions OIDC enterprise-unique issuer URLs.

#### Documentation

Don't believe any documentation needs to be updated. https://docs.sigstore.dev/fulcio/oidc-in-fulcio/#source-repository seems fine enough.

### CODE REVIEW

**Comment by haydentherapper** [comment]
Thanks for the PR @reedloden! Any chance you have a set up such that you can test certificate generation for enterprise GitHub with a private instance of Fulcio? If not, no worries, we'll get this deployed in staging first and I can give pointers on how to test against our staging set up.

**Comment by reedloden** [comment]
> Thanks for the PR @reedloden! Any chance you have a set up such that you can test certificate generation for enterprise GitHub with a private instance of Fulcio? If not, no worries, we'll get this deployed in staging first and I can give pointers on how to test against our staging set up.

I don't have a private instance of Fulcio currently, but if you have a staging environment, happy to do a test against it to confirm everything works.

**Comment by haydentherapper** [comment]
I'll merge this on Monday and ping you once it's rolled out to staging for testing. Thanks!

**Review by haydentherapper — APPROVED** [review]

**Comment by haydentherapper** [comment]
Merging, will ping you once this is in staging.

**Comment by haydentherapper** [comment]
@reedloden The change is in staging. Please follow https://docs.sigstore.dev/cosign/keyless/#public-staging-environment for calling staging. Could you confirm if this works as expected?

**Comment by haydentherapper** [comment]
@reedloden Just pinging to see if you've gotten a chance to take a look

**Pull request merged**
