### PR TITLE
Bump github.com/grpc-ecosystem/grpc-gateway/v2 from 2.15.0 to 2.15.2 …

### PR DESCRIPTION
**Pull request by haydentherapper**
…in /hack/tools

Also update protoc version

### CODE REVIEW

**Comment by haydentherapper** [comment]
still getting a mismatch in generated files

**Comment by cpanato** [comment]
@dependabot recreate

**Comment by cpanato** [comment]
maybe you can rebase this and we try again

**Comment by haydentherapper** [comment]
I'm trying to chase down the issue, seems to be related to the set of protos we've shipped alongside fulcio

**Comment by haydentherapper** [comment]
@bobcallaway including the protos that are bundled with the protoc binary resolved the mismatch.

**Review by bobcallaway — APPROVED** [review]

**Pull request merged**
